In [1]:
pip install pillow --upgrade

Requirement already up-to-date: pillow in c:\users\rahulkushwaha\anaconda3\lib\site-packages (7.2.0)
Note: you may need to restart the kernel to use updated packages.


In [12]:
pip install opencv-contrib-python

^C
Note: you may need to restart the kernel to use updated packages.


In [ ]:
pip install opencv-contrib-python --upgrade --user

In [1]:
import numpy as np
from PIL import Image
import os
import cv2
import pickle
#BASE_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.getcwd()
image_dir = os.path.join(BASE_DIR,"images")
cascade_classifier = cv2.CascadeClassifier('haar/haarcascade_frontalface_alt2.xml')
recognizer = cv2.face.LBPHFaceRecognizer_create()

current_id = 0
label_ids = {}
y_labels = []
x_train = []

for root,dirs,files in os.walk(image_dir):
    for file in files:
        if file.endswith("png") or file.endswith("jpg"):
            path = os.path.join(root,file)
            label = os.path.basename(root).replace(" ","-").lower()
            print(label,path)
            if not label in label_ids:
                label_ids[label] = current_id
                current_id +=1
            id_ = label_ids[label]
            print(label_ids)
            pil_image = Image.open(path).convert("L")#grayscale
            size = (550,550)
            final_image = pil_image.resize(size,Image.ANTIALIAS)
            image_array = np.array(pil_image,"uint8")
            print(image_array)
            faces = cascade_classifier.detectMultiScale(image_array,scaleFactor=1.5,minNeighbors=5)
            for (x,y,w,h) in faces:
                roi = image_array[y:y+h,x:x+w]
                x_train.append(roi)
                y_labels.append(id_)
                
with open("labels.pickle",'wb') as f:
    pickle.dump(label_ids,f)
recognizer.train(x_train,np.array(y_labels))
recognizer.save("trainer.yml")

rahul C:\Users\RahulKushwaha\testproject\images\Rahul\found.png
{'rahul': 0}
[[214 212 211 ...  23  25  80]
 [213 212 207 ...   2  16  73]
 [212 211 209 ...   9   6  71]
 ...
 [ 88 105 108 ...  47  55  66]
 [ 69  76  90 ...  31  43  50]
 [ 76  81  97 ...  39  41  42]]
rahul C:\Users\RahulKushwaha\testproject\images\Rahul\found0.png
{'rahul': 0}
[[240 240 239 ...  30  27  24]
 [240 240 239 ...  30  28  26]
 [240 240 239 ...  29  28  28]
 ...
 [124  74  47 ...  42  42  44]
 [ 63  37  42 ...  43  43  44]
 [ 27  41  61 ...  41  41  46]]
rahul C:\Users\RahulKushwaha\testproject\images\Rahul\found1.png
{'rahul': 0}
[[239 240 240 ...  26  34  40]
 [239 240 240 ...  26  28  30]
 [239 239 239 ...  24  26  26]
 ...
 [ 71  58  70 ...  40  40  40]
 [ 62  63  64 ...  39  42  39]
 [ 49  41  75 ...  40  38  41]]
rahul C:\Users\RahulKushwaha\testproject\images\Rahul\found10.png
{'rahul': 0}
[[239 237 238 ... 198 199 204]
 [237 237 237 ... 201 201 202]
 [237 237 239 ... 196 205 199]
 ...
 [ 78  79  75 

rahul C:\Users\RahulKushwaha\testproject\images\Rahul\found131.png
{'rahul': 0}
[[211 211 211 ... 196 199 200]
 [212 213 213 ... 194 196 198]
 [213 213 213 ... 198 198 198]
 ...
 [114 112 109 ...  50  46  45]
 [113 112 111 ...  50  49  46]
 [113 112 112 ...  49  48  50]]
rahul C:\Users\RahulKushwaha\testproject\images\Rahul\found132.png
{'rahul': 0}
[[211 211 211 ... 214 213 213]
 [211 211 211 ... 212 211 212]
 [210 211 211 ... 207 208 208]
 ...
 [122 121 119 ...  50  47  49]
 [124 120 120 ...  48  48  46]
 [122 119 117 ...  49  50  47]]
rahul C:\Users\RahulKushwaha\testproject\images\Rahul\found133.png
{'rahul': 0}
[[211 211 211 ... 214 213 213]
 [211 211 211 ... 212 211 212]
 [210 211 211 ... 207 208 208]
 ...
 [122 121 119 ...  50  47  49]
 [124 120 120 ...  48  48  46]
 [122 119 117 ...  49  50  47]]
rahul C:\Users\RahulKushwaha\testproject\images\Rahul\found134.png
{'rahul': 0}
[[209 210 210 ... 202 201 205]
 [211 211 210 ... 200 200 200]
 [212 210 210 ... 198 198 198]
 ...
 [142 

rahul C:\Users\RahulKushwaha\testproject\images\Rahul\found168.png
{'rahul': 0}
[[ 68  53  53 ... 148 174 199]
 [ 64  67  73 ...  98 123 139]
 [ 52  55  67 ...  72 118 125]
 ...
 [ 91  91  90 ...   6   5   3]
 [ 91  91  91 ...  24  24   6]
 [ 89  89  89 ...  91  86  89]]
rahul C:\Users\RahulKushwaha\testproject\images\Rahul\found169.png
{'rahul': 0}
[[ 68  53  53 ... 148 174 199]
 [ 64  67  73 ...  98 123 139]
 [ 52  55  67 ...  72 118 125]
 ...
 [ 91  91  90 ...   6   5   3]
 [ 91  91  91 ...  24  24   6]
 [ 89  89  89 ...  91  86  89]]
rahul C:\Users\RahulKushwaha\testproject\images\Rahul\found17.png
{'rahul': 0}
[[156 162 159 ...  22  13   2]
 [154 156 153 ...  21   7   7]
 [150 150 146 ...  20   8   2]
 ...
 [184 183 181 ... 168 168 167]
 [182 182 181 ... 167 167 167]
 [183 183 183 ... 167 168 167]]
rahul C:\Users\RahulKushwaha\testproject\images\Rahul\found170.png
{'rahul': 0}
[[ 26  27  23 ... 173 187 187]
 [ 23  23  21 ... 184 188 191]
 [ 20  19  19 ... 191 192 194]
 ...
 [ 37  

[[222 222 222 ... 214 215 215]
 [222 222 222 ... 211 215 213]
 [221 222 222 ... 215 211 211]
 ...
 [ 40  47  49 ... 113 110  88]
 [ 33  26  28 ... 102 124 101]
 [  5   2   1 ...  51  49  36]]
rahul C:\Users\RahulKushwaha\testproject\images\Rahul\found34.png
{'rahul': 0}
[[221 222 221 ... 217 217 217]
 [221 222 222 ... 217 217 217]
 [222 222 222 ... 217 217 217]
 ...
 [ 50  50  56 ...  36  35  38]
 [ 49  49  51 ...  36  32  35]
 [ 50  47  45 ...  31  31  36]]
rahul C:\Users\RahulKushwaha\testproject\images\Rahul\found35.png
{'rahul': 0}
[[222 224 223 ... 217 218 218]
 [222 222 222 ... 217 217 217]
 [222 222 222 ... 218 218 217]
 ...
 [ 47  49  46 ...  26  31  34]
 [ 50  49  49 ...  26  27  29]
 [ 50  50  47 ...  27  23   4]]
rahul C:\Users\RahulKushwaha\testproject\images\Rahul\found36.png
{'rahul': 0}
[[222 224 223 ... 217 218 218]
 [222 222 222 ... 217 217 217]
 [222 222 222 ... 218 218 217]
 ...
 [ 47  49  46 ...  26  31  34]
 [ 50  49  49 ...  26  27  29]
 [ 50  50  47 ...  27  23  

rahul C:\Users\RahulKushwaha\testproject\images\Rahul\found63.png
{'rahul': 0}
[[ 59  57  47 ... 202 201 201]
 [ 58  59  51 ... 200 201 201]
 [ 57  61  56 ... 200 199 200]
 ...
 [ 96  96  94 ... 119 117 131]
 [ 94  94  93 ... 156 151 148]
 [ 96  96  92 ... 177 170 163]]
rahul C:\Users\RahulKushwaha\testproject\images\Rahul\found64.png
{'rahul': 0}
[[ 59  57  47 ... 202 201 201]
 [ 58  59  51 ... 200 201 201]
 [ 57  61  56 ... 200 199 200]
 ...
 [ 96  96  94 ... 119 117 131]
 [ 94  94  93 ... 156 151 148]
 [ 96  96  92 ... 177 170 163]]
rahul C:\Users\RahulKushwaha\testproject\images\Rahul\found65.png
{'rahul': 0}
[[ 63  63  61 ... 195 198 200]
 [ 45  60  60 ... 195 197 211]
 [ 37  48  53 ... 194 205 209]
 ...
 [ 90  90  90 ... 178 177 179]
 [ 94  94  90 ... 180 177 176]
 [ 94  93  91 ... 181 178 178]]
rahul C:\Users\RahulKushwaha\testproject\images\Rahul\found66.png
{'rahul': 0}
[[ 63  63  61 ... 195 198 200]
 [ 45  60  60 ... 195 197 211]
 [ 37  48  53 ... 194 205 209]
 ...
 [ 90  90 

 [180 179 174 ... 174 176 179]]
rahul C:\Users\RahulKushwaha\testproject\images\Rahul\found91.png
{'rahul': 0}
[[215 214 214 ... 206 206 207]
 [214 213 214 ... 202 201 200]
 [212 212 212 ... 201 194 189]
 ...
 [184 182 184 ... 178 183 177]
 [184 184 185 ... 174 174 172]
 [184 183 184 ... 169 171 170]]
rahul C:\Users\RahulKushwaha\testproject\images\Rahul\found92.png
{'rahul': 0}
[[215 214 214 ... 206 206 207]
 [214 213 214 ... 202 201 200]
 [212 212 212 ... 201 194 189]
 ...
 [184 182 184 ... 178 183 177]
 [184 184 185 ... 174 174 172]
 [184 183 184 ... 169 171 170]]
rahul C:\Users\RahulKushwaha\testproject\images\Rahul\found93.png
{'rahul': 0}
[[211 211 210 ... 182 180 188]
 [206 207 207 ... 129 159 166]
 [205 206 205 ...  90 101 167]
 ...
 [186 186 183 ... 184 177 176]
 [186 185 184 ... 175 175 171]
 [184 185 185 ... 176 174 175]]
rahul C:\Users\RahulKushwaha\testproject\images\Rahul\found94.png
{'rahul': 0}
[[211 211 210 ... 182 180 188]
 [206 207 207 ... 129 159 166]
 [205 206 205 

error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-j8nxabm_\opencv_contrib\modules\face\src\lbph_faces.cpp:362: error: (-210:Unsupported format or combination of formats) Empty training data was given. You'll need more than one sample to learn a model. in function 'cv::face::LBPH::train'


In [2]:
pip install opencv-contrib-python --upgrade --user

  Using cached opencv_contrib_python-4.4.0.42-cp38-cp38-win_amd64.whl (40.2 MB)
Note: you may need to restart the kernel to use updated packages.
